module.exports = {
	'likes': '{ likes, number } me gusta',
	'logout': 'Salir',
	'english': 'Ingles',
	'spanish': 'Español',
	'signup.subheading': 'Regístrate para ver fotos de tus amigos estudiando en Platzi',
	'signup.facebook': 'Iniciar sesión con Facebook',
	'signup.text': 'Iniciar sesión',
	'email': 'Correo electrónico',
	'username': 'Nombre del usuario',
	'fullname': 'Nombre completo',
	'password': 'Contraseña',
	'signup.call-to-action': 'Regístrate',
	'signup.have-account': '¿Tienes una cuenta?',
	'signin': 'Entrar',
	'signup.not-have-account': '¿No tienes una cuenta?',
	'language': 'Idioma',
	'upload-picture' : 'Subir foto',
	'upload': "Subir"
}
